#!/bin/sh

cd lib

cd emulator
make $1 $2 || exit
cd ..

# TODO: Add new libs here
#cd subdir
#make $1 $2 || exit
#cd ..

cd ..

cd kernel
make $1 $2 || exit
cd ..

# TODO: Add new apps here
#cd subdir
#make $1 $2 || exit
#cd ..
